// IMPORTANT: every string in this array MUST be unique, and a valid word (don't use emoji or encoded chars)
// names in this array will be used at random when a new base is created. No two bases may have the same name
// so there must be enough names in the list for each base to use one uniquely or you will be prevented
// from creating a new base.
// shorter names should be preffered
export const baseNames = [
  // https://en.wikipedia.org/wiki/Knights_of_the_Round_Table
  'Accolon',
  'Aglovale',
  'Agravain',
  'Arthur',
  'Bagdemagus',
  'Bedivere',
  'Bors',
  'Brunor',
  'Blumenthal',
  'Cador',
  'Calogrenant',
  'Caradoc',
  'Claudin',
  'Constantine',
  'Dagonet',
  'Dinadan',
  'Ector',
  'Elyan',
  'Erec',
  'Esclabor',
  'Feirefiz',
  'Gaheris',
  'Galahad',
  'Galehault',
  'Galeschin',
  'Gareth',
  'Gawain',
  'Geraint',
  'Gingalain',
  'Gornemant',
  'Griflet',
  'Hector',
  'Hoel',
  'Kay',
  'Lamorak',
  'Lancelot',
  'Lanval',
  'Leodegrance',
  'Lionel',
  'Lucan',
  'Maleagant',
  'Mordred',
  'Morholt',
  'Morien',
  'Palamedes',
  'Pelleas',
  'Pellinore',
  'Percival',
  'Safir',
  'Sagramore',
  'Segwarides',
  'Tor',
  'Tristan',
  'Urien',
  'Yvain',
]
